### ISSUE TITLE
New version of package with serilog 2.x dependency

### ISSUE THREAD

**Issue by mwijnands** [nblumhardt/autofac-serilog-integration#15]
Would it be possible for you to reference serilog 2.x and create a new package?

I am using Serilog 2.4 and just because I use AutofacSerilogIntegration, I have to add Assembly Redirects to Serilog 2.0.0.0 in _every_ project now...

Thanks for the code!

**Comment by nblumhardt** [comment]
Thanks for the reminder! There's already a -dev package out there with 2.x support, but it's time to move it into RTM. Merging https://github.com/nblumhardt/autofac-serilog-integration/pull/16 shortly.
