### ISSUE TITLE
Method not found ModuleRegistration failed 

### ISSUE THREAD

**Issue by akhileshnirapure** [nblumhardt/autofac-serilog-integration#22]
Hi,

I'm trying to use SeriLog, Console Sink, Autofac, AutofactIntegration package in Azure Functions - v1 runtime.

followed the steps
https://github.com/nblumhardt/autofac-serilog-integration

everything works fine if i perform the same in console application/test

but fails to execute in Azure function runtime.

System.MissingMethodException : Method not found: 'Autofac.Core.Registration.IModuleRegistrar AutofacSerilogIntegration.SerilogContainerBuilderExtensions.RegisterLogger(Autofac.ContainerBuilder, Serilog.ILogger, Boolean)'.

Any pointers?

Regards
Akhilesh

**Comment by nblumhardt** [comment]
Hi Akhilesh, no ideas sorry - but I'd guess it's something deployment-related (wrong framework version targeted; old DLL version out there, ...?)

I don't think it's likely to be an issue with this package directly, as it's happy on .NET Framework and Core; closing for now, but please reach out if you think there's something I can do. Cheers!
