### ISSUE TITLE
SourceContext not being injected into BackgroundService (net core 3.1 app autofac5)

### ISSUE THREAD

**Issue by jafin** [nblumhardt/autofac-serilog-integration#27]
Firstly, I don't believe I've correctly identified the problem but will describe as best to my understanding.

In a net core core 3.1 app, we have background services that trigger at startup.  What was being observed was sourcecontext  was set on any log messages, yet it does appear fine on the main web process.

Pulled the code locally and updated to autofac 5, the signature for AttachToComponentRegistration was different so updated.  Created sample scenario site, and observed that the SourceContext prop is now being correctly applied to the backgroundService.

**Comment by nblumhardt** [comment]
Closed in #28
