### ISSUE TITLE
Autofac 6 migration

### ISSUE THREAD

**Issue by slim1305** [nblumhardt/autofac-serilog-integration#39]
Hi,

The Autofac team did a lot of fundametal changes in version 6 [(what's new)](https://autofaccn.readthedocs.io/en/latest/whats-new/upgradingfrom5to6.html).
Specifically:
>RegistrationBuilder.RegistrationData no longer exposes the configured ActivatedHandlers, ActivatingHandlers or PreparingHandlers, and IComponentRegistration no longer exposes Preparing, Activating or Activated events. 

And current "autofac-serilog-integration" version (4.0) throw an exception, because they've removed a couple of used by you methods.
Are you going to fix it soon ?

Thanks,

**Comment by nblumhardt** [comment]
Thanks for the note! No, I don't have any plans to update it, but help would be welcome if anyone is able to send a PR.
