### ISSUE TITLE
Unable to install the package in project framework targeted 4.0

### ISSUE THREAD

**Issue by ammaroff** [nblumhardt/autofac-serilog-integration#4]
The package is not installed if your project framework version = **v4.0**
`Install-Package : Could not install package 'AutofacSerilogIntegration x.x.x'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', 
but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by nblumhardt** [comment]
Hi Ammar, Serilog's dropping .NET 4 from the v2 package, I don't think this package will support it. Should be possible to grab the source and recompile/embed however. Thanks!
