### ISSUE TITLE
Using ILogger from 'Microsoft.Extensions.Logging.Abstractions'

### ISSUE THREAD

**Issue by my-dev-92** [nblumhardt/autofac-serilog-integration#48]
My goal is to inject the Serilog into the host project (.net4.8) and in the domain projects (I use some DDD pattern) use ILogger from 'Microsoft.Extensions.Logging.Abstractions'.
But I see that registering the Serilog is for only the Serilog.ILogger interface and this suggests that I should only use Serilog.ILogger.
Or is the current nuget package not for my case?... 
I saw another nuget [(link)](https://github.com/alsami/Serilog.Extensions.Autofac.DependencyInjection) which allows the use of abstraction from Microsoft.

**Comment by nblumhardt** [comment]
This one's just for Serilog; hopefully the other package covers what you need.

**Comment by my-dev-92** [comment]
> This one's just for Serilog; hopefully the other package covers what you need.

Ok, thanks for fast answer! Any way, I like Serilog :)
